
SUBDIR = finmap \
		 hashtable \
		 listsort \
		 md5 \
		 pickle \
		 pprint \
		 random \
		 regexp \
		 set \
		 sml90 \
		 susp \
		 uref \
		 utest

TESTDIR = finmap \
		  listsort \
		  pickle \
		  regexp

all: lib


lib:
	for dir in $(SUBDIR); do \
		make -C $$dir ; \
	done

.PHONY: test
test: lib
	for dir in $(TESTDIR); do \
		make -C $$dir test ; \
	done

.PHONY: clean
clean:
	for dir in $(SUBDIR); do \
		make -C $$dir $@; \
	done

